version: "3"
services:
  yxi-api:
    image: yximages/yxi-api
    env_file:
      - ./config/api.env
    ports:
      - "8090:8090"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - "api-log:/var/log/yxi"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet

  nginx:
    image: nginx
    deploy:
      replicas: 1
    ports:
      - "9090:80"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "nginx-log:/var/log/nginx/log"
    networks:
      - webnet

networks:
  webnet:

volumes:
  api-log:
  nginx-log: